language: java
notifications:
  email: false
addons:
  sonarcloud:
    organization: "piercirocaliandro"
    token:
      secure: "AI9sQUbObKTY0wCtq7K41UmKTJGae5uu+DpZHRkyVdiebDJMR4HiMZFUhCKESGSjmfYqOsOBenJO3qx4ti9857qiOEsiCuvXnoLdpZnDgYx9GmbNZyDWNHpVNG70MVA54MWvLz6+oeb29VNL5jv2kNIw314Z2fL8GBdtfziM/kvRtWktFnBo+EHJzVZTBT5YQotfkF6K9SserVYXbW1tmduIYcebkqebVAQnUjuwWhoFH1IL3OtRFTPSJHr0igTc8S8ilSURLJy4eXGMbAosXkN6t/zTQwI3z5fHSWnNYdOay1wJV6YcXg9YjSZB2q6KKkSmDKLbxmRX9e2pWD5BbTq1DjGotxWH3Eyx7RAIkjhEKMYaxMabCkhFOQpkbDB/ZEpkOa8BGcnEthPY7/snJEuQqcdCbUaUbtGGsqRx286mPaWXHqfvCIqlz9eaOSZVb1ooQaVp5DcJd4dgq5AfDWinIE0tSMNcYkaTE7l5JwMnj29VytR9xq3t2sD6rLrTcA3OQNjKHTOMn7hg0Fe5hbwjakA2bmGm6SNeOTWgzzZwX94/OuaknrCnLPBqlZel8xn8XEAF0faNcS7Za3Yh/6ac94nFRaOm10Lh7jbKzjVF05qybJJkF3M8a2gKQJHuqxoxgYxUMWEjWiA1izg3u308B/MWOqsolLoqgZpUBA8=" # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar
env:
  global:
    secure: AI9sQUbObKTY0wCtq7K41UmKTJGae5uu+DpZHRkyVdiebDJMR4HiMZFUhCKESGSjmfYqOsOBenJO3qx4ti9857qiOEsiCuvXnoLdpZnDgYx9GmbNZyDWNHpVNG70MVA54MWvLz6+oeb29VNL5jv2kNIw314Z2fL8GBdtfziM/kvRtWktFnBo+EHJzVZTBT5YQotfkF6K9SserVYXbW1tmduIYcebkqebVAQnUjuwWhoFH1IL3OtRFTPSJHr0igTc8S8ilSURLJy4eXGMbAosXkN6t/zTQwI3z5fHSWnNYdOay1wJV6YcXg9YjSZB2q6KKkSmDKLbxmRX9e2pWD5BbTq1DjGotxWH3Eyx7RAIkjhEKMYaxMabCkhFOQpkbDB/ZEpkOa8BGcnEthPY7/snJEuQqcdCbUaUbtGGsqRx286mPaWXHqfvCIqlz9eaOSZVb1ooQaVp5DcJd4dgq5AfDWinIE0tSMNcYkaTE7l5JwMnj29VytR9xq3t2sD6rLrTcA3OQNjKHTOMn7hg0Fe5hbwjakA2bmGm6SNeOTWgzzZwX94/OuaknrCnLPBqlZel8xn8XEAF0faNcS7Za3Yh/6ac94nFRaOm10Lh7jbKzjVF05qybJJkF3M8a2gKQJHuqxoxgYxUMWEjWiA1izg3u308B/MWOqsolLoqgZpUBA8=
